### ISSUE TITLE
Not compatible with PHP 7

### ISSUE THREAD

**Issue by kingkero** [azine/AzineHybridAuthBundle#1]
Just tried to add this Bundle to my Symfony 3 running on PHP 7.0.7, tried to add the bundle via `composer require azine/hybridauth-bundle "dev-master"`.

This resulted in

>   Problem 1
>     - Installation request for azine/hybridauth-bundle dev-master -> satisfiable by azine/hybridauth-bundle[dev-master].
>     - azine/hybridauth-bundle dev-master requires php >=5.6.0 -> your PHP version (7.0.7-2+donate.sury.org~trusty+1) overriden by "config.platform.php" version (5.5.9) does not satisfy that requirement.

**Comment by azine** [comment]
Hi,
from your commit message I read that your php7.0.7 ist running as 5.5.9.

I think it IS compatible with php 5.5.9, but I didn't test it. What do you need? 7.0.7 or 5.5.9?

Cheers,
d.

**Comment by azine** [comment]
PS: version 1.0.0 did run fine with 5.5.x, but not with Symfony 3.x

**Comment by kingkero** [comment]
Ah, totally forgot that I had 5.5.9 with fpm on my local machine. Server runs PHP7 and could install without a problem. Sorry for the misunderstanding on my part
