### ISSUE TITLE
Symfony 3 support

### ISSUE THREAD

**Issue by gadelkareem** [azine/AzineHybridAuthBundle#3]
Currently the bundle requires Symfony2. Any plans for Symfony3 support?

**Comment by azine** [comment]
Plans: yes. 
Schedule: No. 
:-/
Are you using the bundle with Symfony2 currently and thinking about upgrading? or would it be a new installation?

**Comment by gadelkareem** [comment]
New install but I am moving the library from an old project

**Comment by azine** [comment]
Hi,
I updated the composer and travis-ci files. 

Looks like it works with Symfony 3.x

Please give it a try and let me know if you have any problems.

Cheers,
dominik
